# Integração de multas ambientais

Comparar a arrecadação de multas ambientais de RN e PB por tipo de infração, integrando duas bases do IBAMA.

Execute as células em ordem. Este notebook foi revisado a partir de uma atividade acadêmica para apresentação em portfólio.

## Carregamento das bases

In [1]:
# Leitura dos arquivos para DataFrames

import pandas as pd

df_rn = pd.read_csv('dados/arrecadacao_de_multas_ambientais_por_bens_tutelados_RN.csv', sep=";") # leitura do csv do rn
df_pb = pd.read_csv('dados/arrecadacao_de_multas_ambientais_por_bens_tutelados_PB.csv', sep=";") # leitura do csv da pb

## Exploração, conversão monetária e agregação

In [2]:
display(df_rn[["UF", "Tipo Infração", "Valor Pago"]].head()) # exibição das 5 primeiras linhas do dataframe do RN
df_rn.info() # exibição de info do dataframes

print("-" * 60)

display(df_pb[["UF", "Tipo Infração", "Valor Pago"]].head()) # exibição das 5 primeiras linhas do dataframe da PB
df_pb.info() # exibição de info do dataframes

df_rn["Valor Pago"] = (df_rn["Valor Pago"].str.replace(".", "", regex=False).str.replace(",", ".", regex=False).astype(float)) # conversão de valor pago de string para float, assim como tratamento para formatação de moeda BRL

df_pb["Valor Pago"] = (df_pb["Valor Pago"].str.replace(".", "", regex=False).str.replace(",", ".", regex=False).astype(float))  # conversão de valor pago de string para float, assim como tratamento para formatação de moeda BRL

arrecadacao_rn = (df_rn.groupby("Tipo Infração", as_index=False)["Valor Pago"].sum()) # agregação por tipo de infração, assim como a soma dos valores no dataframe do RN

arrecadacao_pb = (df_pb.groupby("Tipo Infração", as_index=False)["Valor Pago"].sum()) # agregação por tipo de infração, assim como a soma dos valores no dataframe da PB

display(arrecadacao_rn)
display(arrecadacao_pb)

   UF       Tipo Infração Valor Pago
0  RN  Controle ambiental    1.255,9
1  RN               Pesca     161,53
2  RN               Pesca     162,88
3  RN               Pesca     165,64
4  RN               Pesca     166,91

<class 'pandas.DataFrame'>
RangeIndex: 53476 entries, 0 to 53475
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Nº AI                         53476 non-null  str
 1   Nome ou Razão Social          53476 non-null  str
 2   CPF/CNPJ                      53398 non-null  str
 3   UF                            53476 non-null  str
 4   Município                     53476 non-null  str
 5   Status Débito                 53476 non-null  str
 6   Tipo Auto                     53476 non-null  str
 7   Tipo Infração                 53476 non-null  str
 8   Enquadramento Legal           39316 non-null  str
 9   Data Auto                     53476 non-null  str
 10  Valor do Auto                 53476 non-null  str
 11  Moeda                         53476 non-null  str
 12  Parcela                       53476 non-null  int64
 13  Quantidade de Parcelas        53476 non-null  int64
 14  Valor (Base) da Parcela       53476 non-null  str
 15  Valor Pago                    53476 non-null  str
 16  Data Pagamento                53476 non-null  str
 17  Última Atualização Relatório  53476 non-null  str
dtypes: int64(2), str(16)
memory usage: 7.3 MB
------------------------------------------------------------

   UF Tipo Infração Valor Pago
0  PB         Fauna      86,99
1  PB         Fauna      87,86
2  PB         Fauna       89,7
3  PB         Fauna      90,61
4  PB         Fauna      90,61

<class 'pandas.DataFrame'>
RangeIndex: 64979 entries, 0 to 64978
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Nº AI                         64979 non-null  str
 1   Nome ou Razão Social          64979 non-null  str
 2   CPF/CNPJ                      64818 non-null  str
 3   UF                            64979 non-null  str
 4   Município                     64979 non-null  str
 5   Status Débito                 64979 non-null  str
 6   Tipo Auto                     64979 non-null  str
 7   Tipo Infração                 64979 non-null  str
 8   Enquadramento Legal           52731 non-null  str
 9   Data Auto                     64979 non-null  str
 10  Valor do Auto                 64979 non-null  str
 11  Moeda                         64979 non-null  str
 12  Parcela                       64979 non-null  int64
 13  Quantidade de Parcelas        64979 non-null  int64
 14  Valor (Base) da Parcela       64979 non-null  str
 15  Valor Pago                    64979 non-null  str
 16  Data Pagamento                64979 non-null  str
 17  Última Atualização Relatório  64979 non-null  str
dtypes: int64(2), str(16)
memory usage: 8.9 MB

                         Tipo Infração   Valor Pago
0             Cadastro Técnico Federal   2529829.90
1                   Controle ambiental  22266834.88
2                                Fauna   1447111.67
3                                Flora   6046985.59
4  Ordenamento urbano e Contr. patrim.     33714.85
5   Org. Gen. Modific. e Biopirataria      22475.18
6                               Outras    377778.15
7                                Pesca   2561922.95
8              Unidades de conservação      1550.77

                         Tipo Infração   Valor Pago
0             Cadastro Técnico Federal   3801198.58
1                   Controle ambiental  21736798.95
2                          Ecossistema     23117.25
3                                Fauna   2807579.92
4                                Flora  14633258.53
5  Ordenamento urbano e Contr. patrim.    174715.55
6   Org. Gen. Modific. e Biopirataria     678715.85
7                               Outras   1321116.20
8                                Pesca    996042.66
9              Unidades de conservação     13390.67

## Integração por tipo de infração

In [3]:
df_integrado = pd.merge(arrecadacao_rn, arrecadacao_pb, on="Tipo Infração", how="outer", suffixes=("_RN", "_PB"), validate="one_to_one")  # integra RN e PB pela coluna "Tipo Infração"

display(df_integrado) # exibe o DataFrame integrado

df_integrado.size # retorna o número total de elementos do DataFrame

                         Tipo Infração  Valor Pago_RN  Valor Pago_PB
0             Cadastro Técnico Federal     2529829.90     3801198.58
1                   Controle ambiental    22266834.88    21736798.95
2                          Ecossistema            NaN       23117.25
3                                Fauna     1447111.67     2807579.92
4                                Flora     6046985.59    14633258.53
5  Ordenamento urbano e Contr. patrim.       33714.85      174715.55
6   Org. Gen. Modific. e Biopirataria        22475.18      678715.85
7                               Outras      377778.15     1321116.20
8                                Pesca     2561922.95      996042.66
9              Unidades de conservação        1550.77       13390.67

30

## Análise de completude

In [4]:
print(df_integrado.isna().sum()) # conta os valores ausentes em cada coluna

print("Total de dados ausentes:", df_integrado.isna().sum().sum()) # conta o total de valores ausentes no DataFrame

Tipo Infração    0
Valor Pago_RN    1
Valor Pago_PB    0
dtype: int64
Total de dados ausentes: 1

## Interpretação

Cada registro representa um pagamento/parcela: a soma considera os valores pagos, não o valor nominal das multas. O `outer merge` conserva os tipos de infração encontrados em qualquer estado. Valores ausentes após a integração não são automaticamente substituídos por zero. A análise é descritiva e não permite comparar desempenho de fiscalização sem considerar população, período e contexto.